version: "3.0"
services:
  database:
    image: "postgres:16-alpine"
    container_name: "postgres-next"
    env_file:
      - ./var/.env
    volumes:
      - ./var/database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - frontend-next

networks:
  frontend-next: